# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c7-GnZlImowezPXW7uQq5-sdk7i_lBvw

0보다 크거나 같은 정수 N이 주어진다. 이때, N!을 출력하는 프로그램을 작성하시오.
"""

a = int(input())
answer = 1
for i in range(a, 0, -1):
  answer *= i

if a == 0:
  print(1)
else:
  print(answer)